packages:
  - "packages/*"
  - "models/*"
  - "plugins/*"
  - "server/*"
  - "server-plugins/*"
  - "services/**/model-*"
  - "services/**/pod-*"
  - "workers/*"
  - "dev/*"
  - "desktop"
  - "desktop-package"
  - "templates/*"
