// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  TRANSACTOR: DurableObjectNamespace

  SERVER_SECRET: string

  HYPERDRIVE: Hyperdrive

  ACCOUNTS_URL: string

  DB_URL: string
}
