#:schema node_modules/wrangler/config-schema.json
name = "cloud-transactor-rpc-demo"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[vars]
ACCOUNTS_URL = "http://127.0.0.1:3000"

[[services]]
binding = "TRANSACTOR_SERVICE"
service = "cloud-transactor"
entrypoint = "TransactorRpc"
