#:schema node_modules/wrangler/config-schema.json
name = "cloud-transactor-http-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[[services]]
binding = "TRANSACTOR_SERVICE"
service = "cloud-transactor"
entrypoint = "TransactorRpc"
