//
// Copyright © 2026 Hardcore Engineering Inc.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//

import { type BackupInfo } from '../types'

/**
 * Shape of the data returned from `<backupUrl>/<workspace>/index.json`.
 * Mirrors the inline type used by the backup settings page.
 */
export interface BackupIndex {
  files?: Array<{ name: string, size: number }>
  info?: BackupInfo
}

const ROOT_FILES = ['index.json', 'backup.json.gz', 'blob-info.json.gz']

/**
 * Collect the complete, de-duplicated list of backup file names that make up a
 * full backup. The order is stable: well-known root files first, then every
 * file advertised in the index, then any per-snapshot domain files that were
 * not already listed.
 */
export function collectBackupFileNames (index: BackupIndex | undefined): string[] {
  const seen = new Set<string>()
  const result: string[] = []

  const add = (name: string | undefined): void => {
    if (name === undefined || name === '' || seen.has(name)) {
      return
    }
    seen.add(name)
    result.push(name)
  }

  for (const name of ROOT_FILES) {
    add(name)
  }

  for (const file of index?.files ?? []) {
    add(file.name)
  }

  for (const snapshot of index?.info?.snapshots ?? []) {
    for (const domain of Object.values(snapshot.domains)) {
      domain.storage?.forEach(add)
      domain.snapshots?.forEach(add)
      add(domain.snapshot)
    }
  }

  return result
}

export interface BackupScriptOptions {
  /** Base url including the workspace segment, e.g. `https://host/backup/<wsId>`. */
  baseUrl: string
  /** File names to download (see {@link collectBackupFileNames}). */
  files: string[]
  /** Folder name the script will write into. Defaults to `huly-backup`. */
  outDir?: string
  /** Optional `RESTORE.md` contents to drop next to the downloaded files. */
  restoreReadme?: string
}

/**
 * Generate a self-contained POSIX shell script that downloads every backup file
 * with `curl`, preserving the directory layout.
 *
 * The bearer token is intentionally NOT embedded: the script reads it from the
 * `HULY_BACKUP_TOKEN` environment variable or prompts for it at runtime, so the
 * generated text is safe to save and share. The downloaded folder is a valid
 * backup directory that `tool backup-restore` can consume directly.
 */
export function generateBackupScript (options: BackupScriptOptions): string {
  const { baseUrl, files } = options
  const outDir = options.outDir ?? 'huly-backup'
  const normalizedBase = baseUrl.replace(/\/+$/, '')

  const downloads = files.map((name) => `download ${shellQuote(name)}`).join('\n')

  const readmeBlock =
    options.restoreReadme !== undefined
      ? `
cat > "$OUT_DIR/RESTORE.md" <<'HULY_RESTORE_EOF'
${options.restoreReadme}
HULY_RESTORE_EOF
echo "Restore instructions written to $OUT_DIR/RESTORE.md"
`
      : ''

  return `#!/usr/bin/env bash
# Huly workspace backup downloader.
# Generated by the Huly backup settings page.
# The bearer token is read from $HULY_BACKUP_TOKEN or prompted for at runtime,
# so this script contains no secrets and is safe to save and share.
set -euo pipefail

BASE_URL=${shellQuote(normalizedBase)}
OUT_DIR=${shellQuote(outDir)}
TOKEN="\${HULY_BACKUP_TOKEN:-}"

if [ -z "$TOKEN" ]; then
  read -rsp 'Paste Huly backup bearer token: ' TOKEN
  echo
fi
if [ -z "$TOKEN" ]; then
  echo 'A bearer token is required.' >&2
  exit 1
fi

download() {
  local rel="$1"
  local dest="$OUT_DIR/$rel"
  mkdir -p "$(dirname "$dest")"
  echo "Downloading $rel"
  curl -fSL -H "Authorization: Bearer $TOKEN" "$BASE_URL/$rel" -o "$dest"
}

${downloads}
${readmeBlock}
echo "Done. Backup saved to $OUT_DIR"
`
}

export interface RestoreReadmeOptions {
  /** Source workspace id the backup was taken from. */
  sourceWorkspace: string
  /** Number of backup files in the archive/folder. */
  fileCount: number
}

/**
 * Build the contents of a `RESTORE.md` that ships alongside the backup so it can
 * be restored into any other Huly setup with the platform admin tool.
 */
export function generateRestoreReadme (options: RestoreReadmeOptions): string {
  const { sourceWorkspace, fileCount } = options

  return `# Restoring this Huly backup

This folder is a copy of the backup files for workspace \`${sourceWorkspace}\`
(${fileCount} files). It can be restored into any Huly setup using the platform
admin tool.

## Steps

1. Copy this folder onto the machine running the target Huly platform.

2. Create the destination workspace (and its owner) if it does not exist yet,
   using your normal workspace-creation flow.

3. From the platform monorepo, restore the backup into that workspace:

       cd dev/tool
       rushx tool backup-restore <path-to-this-folder> <target-workspace>

   Add \`--upgrade\` if the target runs a newer model version.

## Notes

- Keep \`index.json\` and all \`*.gz\` files together; the restore tool reads the
  folder as a single backup directory.
- These files contain every document and every blob that was included in the
  backup. Blobs the backup intentionally skips — video, audio, and files larger
  than the server's blob limit — are listed in \`blob-info.json.gz\` but their
  contents are NOT included here; they remain in the source workspace's live
  storage.
`
}

/** Quote a value for safe use inside single quotes in a POSIX shell. */
function shellQuote (value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`
}

let crcTable: Uint32Array | undefined

function getCrcTable (): Uint32Array {
  if (crcTable !== undefined) {
    return crcTable
  }
  const table = new Uint32Array(256)
  for (let n = 0; n < 256; n++) {
    let c = n
    for (let k = 0; k < 8; k++) {
      c = (c & 1) !== 0 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    }
    table[n] = c >>> 0
  }
  crcTable = table
  return table
}

/** Compute the CRC-32 checksum (as required by the ZIP format) of a buffer. */
export function crc32 (data: Uint8Array): number {
  const table = getCrcTable()
  let crc = 0xffffffff
  for (let i = 0; i < data.length; i++) {
    crc = table[(crc ^ data[i]) & 0xff] ^ (crc >>> 8)
  }
  return (crc ^ 0xffffffff) >>> 0
}

export interface ZipEntry {
  name: string
  data: Uint8Array
}

/**
 * Build an uncompressed (STORE method) ZIP archive in memory. The backup files
 * are already gzip-compressed, so storing them avoids pointless re-compression
 * while still producing a single, portable archive.
 *
 * Note: this implementation does not emit ZIP64 records, so it is limited to
 * archives below 4 GiB. For larger backups use the generated download script.
 */
export function buildStoreZip (entries: ZipEntry[]): Uint8Array<ArrayBuffer> {
  const encoder = new TextEncoder()
  const locals: Uint8Array[] = []
  const central: Uint8Array[] = []
  let offset = 0

  for (const entry of entries) {
    const nameBytes = encoder.encode(entry.name)
    const crc = crc32(entry.data)
    const size = entry.data.length

    const localHeader = new Uint8Array(30 + nameBytes.length)
    const lv = new DataView(localHeader.buffer)
    lv.setUint32(0, 0x04034b50, true) // local file header signature
    lv.setUint16(4, 20, true) // version needed
    lv.setUint16(6, 0x0800, true) // flags: UTF-8 names
    lv.setUint16(8, 0, true) // method: store
    lv.setUint16(10, 0, true) // mod time
    lv.setUint16(12, 0x21, true) // mod date (1980-01-01)
    lv.setUint32(14, crc, true)
    lv.setUint32(18, size, true) // compressed size
    lv.setUint32(22, size, true) // uncompressed size
    lv.setUint16(26, nameBytes.length, true)
    lv.setUint16(28, 0, true) // extra length
    localHeader.set(nameBytes, 30)

    locals.push(localHeader, entry.data)

    const centralHeader = new Uint8Array(46 + nameBytes.length)
    const cv = new DataView(centralHeader.buffer)
    cv.setUint32(0, 0x02014b50, true) // central directory signature
    cv.setUint16(4, 20, true) // version made by
    cv.setUint16(6, 20, true) // version needed
    cv.setUint16(8, 0x0800, true) // flags: UTF-8 names
    cv.setUint16(10, 0, true) // method: store
    cv.setUint16(12, 0, true) // mod time
    cv.setUint16(14, 0x21, true) // mod date
    cv.setUint32(16, crc, true)
    cv.setUint32(20, size, true) // compressed size
    cv.setUint32(24, size, true) // uncompressed size
    cv.setUint16(28, nameBytes.length, true)
    cv.setUint16(30, 0, true) // extra length
    cv.setUint16(32, 0, true) // comment length
    cv.setUint16(34, 0, true) // disk number
    cv.setUint16(36, 0, true) // internal attrs
    cv.setUint32(38, 0, true) // external attrs
    cv.setUint32(42, offset, true) // local header offset
    centralHeader.set(nameBytes, 46)

    central.push(centralHeader)

    offset += localHeader.length + size
  }

  const centralSize = central.reduce((sum, b) => sum + b.length, 0)
  const eocd = new Uint8Array(22)
  const ev = new DataView(eocd.buffer)
  ev.setUint32(0, 0x06054b50, true) // end of central directory signature
  ev.setUint16(4, 0, true) // disk number
  ev.setUint16(6, 0, true) // central dir start disk
  ev.setUint16(8, entries.length, true) // entries on this disk
  ev.setUint16(10, entries.length, true) // total entries
  ev.setUint32(12, centralSize, true) // central dir size
  ev.setUint32(16, offset, true) // central dir offset
  ev.setUint16(20, 0, true) // comment length

  const parts = [...locals, ...central, eocd]
  const total = parts.reduce((sum, b) => sum + b.length, 0)
  const out = new Uint8Array(total)
  let pos = 0
  for (const part of parts) {
    out.set(part, pos)
    pos += part.length
  }
  return out
}
