
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: app
          image: hardcoreeng/front
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
          - name: ACCOUNTS_URL
            value: https://account.hc.engineering/
          - name: COLLABORATOR_URL
            value: https://collaborator.hc.engineering/
          - name: UPLOAD_URL
            value: /files
          - name: TRANSACTOR_URL
            value: wss://transactor.hc.engineering/
          - name: GMAIL_URL
            value: gmail.hc.engineering
          - name: ELASTIC_URL
            valueFrom:
              secretKeyRef:
                name: elastic
                key: url
          - name: MINIO_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: minio
                key: endpoint
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: accessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: secretKey
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  selector:
    app: front
  ports:
    - port: 80
      targetPort: 8080
