// Generated by Wrangler on Sat Jul 06 2024 18:52:21 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
  datalake_blobs: KVNamespace;
  datalake_eu_west: R2Bucket;
  HYPERDRIVE: Hyperdrive;
  STREAMS_ACCOUNT_ID: string;
  STREAMS_AUTH_KEY: string;
  S3_UPLOAD_ACCOUNT_ID: string;
  S3_UPLOAD_KEY: string;
  S3_UPLOAD_SECRET: string;
  S3_UPLOAD_BUCKET: string;
  S3_UPLOAD_REGION: string;
}
